version: '3.5.6'
services:

  rasa:
    image: rasa-server-okteto:latest
    build: "./"
    volumes:
    - ./data: /app/data
    - ./actions:/app/actions
    - ./tests:/app/tests
    command: bash -c "rm -rf models/* && rasa train && rasa run --enable-api --cors \"*\""
    working_dir: /app
    ports:
    - '5006:5005'
    public: true
    networks:
    - all

  rasa-actions:
    image: rasa-server-okteto:latest
    build: "./"
    volumes:
    - ./actions: /app/actions
    command: bash -c "rasa run actions"
    working_dir: /app
    ports:
    - '5055:5055'
    networks:
    - all

networks:
  all:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
